openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: This is a sample API to demonstrate OpenAPI specification.
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: openapi@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}